// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
export const MISSING_SUPABASE_CONFIG_MESSAGE =
  "Supabase environment variables are missing. Create a .env file from .env.example.";
export const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!hasSupabaseConfig) {
  console.error(MISSING_SUPABASE_CONFIG_MESSAGE);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createDisabledSupabaseClient(): SupabaseClient<Database> {
  const handler: ProxyHandler<(...args: unknown[]) => unknown> = {
    get(_target, prop) {
      if (prop === "then") return undefined;
      if (prop === Symbol.toStringTag) return "DisabledSupabaseClient";
      return new Proxy(() => {}, handler);
    },
    apply() {
      throw new Error(MISSING_SUPABASE_CONFIG_MESSAGE);
    },
  };

  return new Proxy(() => {}, handler) as unknown as SupabaseClient<Database>;
}

export const supabase: SupabaseClient<Database> = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createDisabledSupabaseClient();
